version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/atlas"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "cargo"
    directory: "/remote-client"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "cargo"
    directory: "/switchboard"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
